// Generated by https://quicktype.io

export interface Campaign {
  id:        number;
  name:      string;
  region:    string;
  createdOn: number;
  price:     Price;
  csv:       string;
  report:    string;
  image_url: string;
}

export interface Price {
  weekly:     number;
  yearly:     number;
  halfYearly: number;
}
