// Generated by https://quicktype.io

export interface Campaign {
  id: number;
  name: string;
  region: string;
  createdOn: number;
  price: string;
  csv: string;
  report: string;
  image_url: string;
}
