import LocalizedStrings from "react-localization";

export const strings = new LocalizedStrings({
  en: {
    manageCampaigns: "Manage Campaigns",
    "Upcoming Campaigns": "Upcoming Campaigns",
    "Live Campaigns": "Live Campaigns",
    "Past Campaigns": "Past Campaigns",
    date: "Date",
    campaign: "Campaign",
    view: "View",
    actions: "Actions",
    days: "Days",
    ago: "ago",
    ahead: "ahead",
    today: "Today",
    loading: "Loading",
    noCampaignsAvailable: "No campaigns available under this category!",
    report: "Report",
    scheduleAgain: "Schedule again",
    pricing: "Pricing",
    close: "Close",
    done: "Done",
    chooseNewDate: "Choose new date",
  },
  hi: {
    manageCampaigns: "अभियान प्रबंधित करें",
    "Upcoming Campaigns": "आगामी अभियान",
    "Live Campaigns": "लाइव अभियान",
    "Past Campaigns": "पिछले अभियान",
    date: "तारीख",
    campaign: "अभियान",
    view: "देखें",
    actions: "कार्रवाई",
    days: "दिन",
    ago: "पूर्व",
    ahead: "आगे",
    today: "आज",
    loading: "लोड हो रहा है",
    noCampaignsAvailable: "इस श्रेणी के अंतर्गत कोई अभियान उपलब्ध नहीं है!",
    report: "रिपोर्ट",
    scheduleAgain: "फिर से शेड्यूल करें",
    pricing: "मूल्य निर्धारण",
    close: "बंद करे",
    done: "पूर्ण",
    chooseNewDate: "नई तारीख चुनें",
  },
});
